---
title: "LeaDeLe - Learning Deep Learning"
author: "Cyrille Mascart"
date: "February 03, 2021"
output:
  html_document:
    df_print: paged
---

This is a small tutorial about learning deep learning, with a bit of theory, some applications and a lot of fun!

I am building this notebook as a testament of my training and learning of machine learning, and deep learning in particular. I will consider that the reader have the same knowledge as I have about deep learning, and has the same required knowledge. Since I own a Ph.D. in computer science, I expect that basic programming skills and basic math knowledge have been acquired by the reader.

I have based myself on several books and tutorials. Here is the list of the most importants:

-   <https://srdas.github.io/DLBook>: a simple introduction, with examples in R, designed for Business Analytics students.

# Requirements

Knowing a bit of the following is necessary. Languages:

- C++

- R

Mathematics:

- Linear Algebra

- Probability

# Supervised learning

## Linear Model

#### Model

#### Code

```{Rcpp DataDefinitions}
#include <Rcpp.h>
#include <vector>

/**
 * @brief A generic Image.
 *
 * An Image is an item to be classified: a number, a picture, etc.
 * This is a simple decorator over a std::vector<double>, which adds some information about the diemnsions of the image, as well as the label to be learnt.
 *
 * In the case of a 2-D picture, the linearilization is column major:
 * 123
 * 456 -> 123456789
 * 789
 */
struct Image: public std::vector<double> {
public:
  /**
   * @brief Simple constructor.
   * @param _rows Number of rows.
   * @param _columns Number of columns.
   * @param _label Label of the image.
   */
  Image(int _rows, int _columns, int _label): std::vector<double>(_rows * _columns), rows(_rows), columns(_columns), label(_label) {}

  int rows; /**< Number of rows of the image. */
  int columns; /**< Number of columns of the image. */
  int label; /**< Label of the image. */
};

/**
 * @brief A basic Data, contains the images to be classified (either training or test set).
 */
struct Data: public std::vector<Image> {
  int32_t nbr_images ;
  int32_t nbr_rows   ;
  int32_t nbr_columns;
  int32_t nbr_labels;
};
```
